tests: Switch to HSpec
Tasty has pretty terrible driver – it just prints stuff like

        Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "main", srcLocModule = "Semer.Tests", srcLocFile = "tests/Semer/Tests.hs", srcLocStartLine = 56, srcLocStartCol = 9, srcLocEndLine = 56, srcLocEndCol = 22})) (ExpectedButGot Nothing "[SemanticError [()] \"Variable b was declared as \\8216bool\\8217 but it was set to \\8216i32\\8217.\"]" "[]")

Instead of properly formatting it.